SELECT * FROM sistemaoa.materia;

INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Algebra I');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Análisis');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Mecánica Clásica I');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Métodos Matemáticos para la Física');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Electromagnetismo');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Métodos Matemáticos para la Fïsica');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Análisis Complejo');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Lab. de Electromagnetismo');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Oscilaciones y Ondas');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Óptica');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Lab. de Óptica');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Introducción a la Física Cuántica');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Electrodinámica Clásica I');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Mecánica Clásica II');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Ecuaciones Diferenciales Parciales');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Física Térmica');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Electrodinámica Clásica II');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Física Atómica y Molecular');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Lab. de Física Atómica y Molecular');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Electrónica');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Instrumentación');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Física Nuclear y de Partículas');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Física Computacional I');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Mecánica Cuántica I');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Mecánica Estadística');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Mecánica Cuántica II');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Física Computacional II');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Física Experimental');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Historia de la Física');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (1, 'Estado Sólido');

INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Álgebra I');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Análisis Real');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Análisis Complejo');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Análisis Matemático I');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Análisis Numérico I');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Análisis de Foureir y aplicaciones a las EDP');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Investigación Operativa');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Teoría de la Medida');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Análisis Matemático II');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Análisis Numérico II');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Álgebra II');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Optimización I');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Modelos en Economía');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Optimización II');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Topología');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Ecuaciones Diferenciales Parciales');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Análisis Matemático III');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Teoría de Probabilidades');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Procesos Estocásticos');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Análisis Matemático IV');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Ecuaciones Diferenciales Parciales II');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Geometría');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Ecuaciones Diferenciales Parciales II');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Análisis Matemático IV');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Geometría II');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Análisis numérico para las EPD');
INSERT INTO `materia`(`idCarrera`, `nombreCarrera`)  VALUES (2, 'Control Óptimo');